function [h,p,kstat,cv]=ks(x)

% Input:  x: 1-d dataset
     
% Output: h = 1/0 if the dataset is unimodal/multimodal
%         p: p-value of the hypothesis test,
%         kstat: the value of the test statistic
%         cv: approximate critical value of the test.

% This method uses Kolmogorov-Smirnov test to check if a dataset is
% generated by the Uniform distribution

if length(x)>1
    dist = makedist('uniform','Lower',min(x),'Upper',max(x));
    [h,p,kstat,cv] = kstest(x,'CDF',dist,'Alpha',0.01);
    h=1-h;
else
    h=1;
end
end